### ISSUE TITLE
Readme introduction provides no reference point

### ISSUE THREAD

**Issue by Draugr-official** [WebWorks-Dev/WebFlow#1]
The current state of the readme doesnt tell the user assumptions required to be met when using webflow.
Does it need a specific database structure? Does it require have two seperate databases, one for authentication and one for user info?

**Comment by S-IERRA** [comment]
Hey sorry for the late reply, apart from when you use [RequiresEmailVerification] attribute which will force you to add [RegistrationToken] and [PasswordResetToken] to your object model, there is no need to alter the database in any way as all other attributes are just metadata
